all: bidding_system.c host.c player.c player_bonus.c
	gcc bidding_system.c -o bidding_system
	gcc host.c -o host
	gcc player.c -o player
	gcc player_bonus.c -o player_bonus
clean:
	rm -f bidding_system host player player_bonus
